# Site
title:          Fábio Souza
bio:            'Electrical Engineer, Entrepreneur, and Teacher'
description:    "Fabio souza, engenheiro com experiência no desenvolvimento de projetos eletrônicos embarcados. Trabalhou com ensino técnico de eletrônica e programação. Hoje é diretor de operações do portal Embarcados, onde trabalha para levar conteúdo de eletrônica, sistemas embarcados e IoT para o Brasil. 

Entusiastas do movimento maker, DIY e do compartilhamento de conhecimento, publica diversos artigos sobre eletrônica e sistemas Embarcados, além de projetos open hardware. É líder do projeto Franzininho, uma placa compatível com a Arduino e mantida pela comunidade. Realiza palestras, cursos e workshops onde leva conhecimento para as pessoas de forma presencial. 

Confira as atualizações no blog e os projetos que estou trabalhando. Se você quiser entrar em contato, sinta-se à vontade para entrar em contato através das redes sociais abaixo."
picture:        'assets/img/profile.png'
locale:         en_US
url:            https://FBSeletronica.github.io


# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
# if you don't have any of social below, comment the line.
#email:
twitter: FBSeletronica
facebook: fabio.souza.77398
#google:
  #plus: #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
github: FBSeletronica
#stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin: username
#xing: username
instagram: fabiosouza.io
#lastfm: username
#tumblr: username
#pinterest: username
#foursquare: username
#steam: username
#dribbble: username
#youtube: username
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username

# Paginate
# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"


# Comments
disqus_shortname: alperenbozkurt-net


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
